### ISSUE TITLE
Record Info Shows Wrong Message for Missing Records

### ISSUE THREAD

**Issue by LinnZawWin** [neronotte/Greg.Xrm#19]
**Describe the bug**
Selecting the rows with LeftMissing or RightMissing result in **Comparison Result Details** and going to **Record Info** tab shows more info about "The record is present only on XYZ". The environment name in that message is showing the other way round.

**To Reproduce**
1. Execute comparison
2. Selecting the rows with LeftMissing which is Orange and the legend below says "Missing on <<ENV1 Name>>"
3. Click on **Record Info** tab
4. The **Record Info** message says "The record is present only on <<ENV1 Name>>"

**Expected behavior**
The **Record Info** message should "The record is present only on <<ENV**2** Name>>"

**Screenshots**
![](https://i.imgur.com/jEI8HV5.png)

**Comment by neronotte** [comment]
Thank you for your feedback. It's fixed in release 1.2021.1.13
