### ISSUE TITLE
How to use/no entities loaded?

### ISSUE THREAD

**Issue by simes1** [neronotte/Greg.Xrm#27]
I don't seem to be able to get this work but maybe I'm not using it correctly.

When I click Load entities button it says it is loading entities but then I see nothing and cannot execute a compare.

---
- Deployment: Online
- DB Version: 9.2.21014.132
- Connection Controls Version: 1.2021.1.39
- XrmToolBox Version: 1.2021.1.44
- Tool Version: 1.2021.2.5

**Comment by neronotte** [comment]
Hi,
The "load entities" button downloads entity metadata from the first environment you selected, and allows you to choose the entities to compare. After clicking "Load tables" you will be able to click on the "Add table" button that allows you to configure the entities to compare and the comparison criteria.

If you have any doubt on how to use the tool you can press F1 in the Configurator view, and an help pane shows on the right describing what you can do.

**Comment by simes1** [comment]
Ah OK - sorry I didn't realise that.  Now I see...

BTW F1 for help does not appear to display anything on my machine.  I briefly get a circle of patience but nothing is displayed.

Regards

--
Simon

**Comment by neronotte** [comment]
Can you send me a screenshot of what you see when you press F1?

**Comment by simes1** [comment]
It's very quick but I'll try...

**Comment by simes1** [comment]
Too quick for a screen shot...

I wonder if I can paste the video clip I took here?

too big...

**Comment by neronotte** [comment]
If you want you can use https://transferxl.com/ or sites like that to share it

**Comment by simes1** [comment]
Try again..

https://user-images.githubusercontent.com/11423243/108230141-5ac68900-7138-11eb-8d50-7a12b451719b.mp4

So I click in an panel and press F1 I briefly see the circle but nothing else.  I did this a couple of times left and right - the video only captures two of them I think - they are quite quick.

**Comment by neronotte** [comment]
OK, I've seen the bug. Fix will be deployed in a couple of minutes.

Best regards
_neronotte
