### ISSUE TITLE
Unable to Add Multiple Environments in _n.EnvironmentSolutionsComparer

### ISSUE THREAD

**Issue by LinnZawWin** [neronotte/Greg.Xrm#32]
**Describe the bug**
In _n.EnvironmentSolutionsComparer tool, adding the environment would replace the existing environment and I am not able to connect multiple to compare.

**To Reproduce**
1. Open the tool and connect one of the environments.
2. Click on 'Add environment' button
3. Connection environment
4. In the **Environment** pane, the newly connected environment replaced the existing environment.

**Expected behavior**
Both existing and new environment is connected and both of them are shown in the environment pane on the left side.

**Screenshots**
When the first environment is connected
![image](https://user-images.githubusercontent.com/14156926/111442618-6922b780-876d-11eb-9ede-a5c3d37ed48c.png)

When the second environment is connected
![image](https://user-images.githubusercontent.com/14156926/111442651-72ac1f80-876d-11eb-8c19-d50c35b9aaf9.png)

**Desktop (please complete the following information):**
 - Version 1.2021.3.1

**Comment by neronotte** [comment]
Hi Lin,
the tool uses the ConnectionDetail.EnvironmentId property to check whether an environment is already "connected" (and, in case, replace it into the list) or not (and, in case, add it to the list).

The ConnectionDetail class is the one provided OOTB by XrmToolbox. The EnvironmentId is took from the ConnectionList.Default.xml file, that can be found in the Connections folder, and it's assumed to be unique for each connection endpoint.

Did you manually edited that file? could you check if in that file the two connections you tried to make have the same EnvironmentId?
If so, could you please check if those two connections have different values on the ConnectionId node? (maybe this one is ensured to be unique).

Best regards,
Riccardo

**Comment by Guyanthalas** [comment]
I'm having the same issue. I know that I haven't edited the file in question. I actually can't even find the file... any idea where it would be located?

**Comment by neronotte** [comment]
Hi,
it is located in the XrmToolBox folder:
![image](https://user-images.githubusercontent.com/1436173/111758141-6a9ecd80-889c-11eb-9f34-f3a208e6f9a6.png)

under Connections:
![image](https://user-images.githubusercontent.com/1436173/111758188-78ece980-889c-11eb-9fe2-80e53343c7d3.png)

In the next version (build will be available in the next couple of minutes) I've changed the "distict by EnvironmentId" with a "distinct by ConnectionId", and this should actually be unique. Let me kwow if it works

**Comment by LinnZawWin** [comment]
Great! That should fix the issue. I checked the connection files and seems like <EnvironmentId> was introduced on 30 Jan 2020 in 
[#107](https://github.com/MscrmTools/MscrmTools.Xrm.Connection/commit/7acbb5e66232631417983dc235dbc7a0360caa19#diff-5191b1c3df60da4ab0fbdc2d8521c0d1a50acd37d576f66614f3ab9dc0624c08) and connections created before that date do not have the <EnvironmentId> tag in the ConnectionDetail.

**Comment by Guyanthalas** [comment]
Tested, verified fixed on my end!

**Comment by LinnZawWin** [comment]
Thanks, tested and working in 1.2021.3.2
