### ISSUE TITLE
Ability to compare records with the same title but different entries inside the record. _n.EnvironmentComparer

### ISSUE THREAD

**Issue by Azasle** [neronotte/Greg.Xrm#38]
**Is your feature request related to a problem? Please describe.**
When attempting to compare entities with entries that have same title, the _n.EnvironmentComparer tool will fail:

{
  "ClassName": "Greg.Xrm.EnvironmentComparer.Engine.ComparisonException",
  "Message": "Comparer <ENTITY> by key <TITLE>: List2 contains duplicate values by key!",
  "Data": null,
  "InnerException": null,
  "HelpURL": null,
  "StackTraceString": "   at Greg.Xrm.EnvironmentComparer.Engine.GenericCollectionComparer`1.Compare(IReadOnlyCollection`1 list1, IReadOnlyCollection`1 list2)\r\n   at Greg.Xrm.EnvironmentComparer.Engine.CompareEngine.Compare(EntityComparer comparer)\r\n   at Greg.Xrm.EnvironmentComparer.Engine.CompareEngine.CompareAll()\r\n   at Greg.Xrm.EnvironmentComparer.Views.Configurator.ConfiguratorViewModel.ExecuteComparison(IReadOnlyCollection`1 entitiesToCompare)\r\n   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)\r\n   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)",
  "RemoteStackTraceString": null,
  "RemoteStackIndex": 0,
  "ExceptionMethod": "8\nCompare\nGreg.Xrm.EnvironmentComparer, Version=1.2022.1.2, Culture=neutral, PublicKeyToken=null\nGreg.Xrm.EnvironmentComparer.Engine.GenericCollectionComparer`1\nSystem.Collections.Generic.IReadOnlyCollection`1[Greg.Xrm.EnvironmentComparer.Engine.ObjectComparison`1[T]] Compare(System.Collections.Generic.IReadOnlyCollection`1[T], System.Collections.Generic.IReadOnlyCollection`1[T])",
  "HResult": -2146233088,
  "Source": "Greg.Xrm.EnvironmentComparer",
  "WatsonBuckets": null
}

**Describe the solution you'd like**
The ability to compare entities with records with the same title.

**Comment by neronotte** [comment]
Hi,
The key for comparison must be unique, it means that you cannot have two records on the same environment with a given key.
In your case, you have 2 records with the same Title on the “second” environment, and this breaks the comparison process.
I’ll make the error more understandable.
